hash-format = "sha256"

[[files]]
file = "README.md"
hash = "ba5c3c4cf297b08664493f40339b37a18bc75a11f2c072c24b8d3aaf7f50a0ab"

[[files]]
file = "config/computercraft-client.toml"
hash = "43da4c2af45ac23ea300941688f42d15c4f67d7d7a7018c0b91782cf3ae90c1d"

[[files]]
file = "files/aurorasdecorations-1.0.0+1.18.jar"
hash = "b1b55aa8595c5255ce05ba4dda26dbc8b1310f01e4944613e185d20b5f2ae0b2"

[[files]]
file = "files/create-mc1.18.1_v0.4d+482.jar"
hash = "43987243f523ec5ef3dc229e3a955f3be7719ee8e7a6cc0dfe4bdf463805293e"

[[files]]
file = "mods/adorn.toml"
hash = "9e1570931cdc5f206c7d98ece305cd47e419c50c5faa50b520e7f44ac19848e0"
metafile = true

[[files]]
file = "mods/advancementinfo.toml"
hash = "7a788032ed19bb951344c3fae94538657ee6a06f90d4e378a39b7ba0b83ccce9"
metafile = true

[[files]]
file = "mods/ae2.toml"
hash = "a02dbb9a8ee618eb233baa0e9346a3a8442c5cf02716f780235d8d8ab8d70d97"
metafile = true

[[files]]
file = "mods/animatica.toml"
hash = "139cd6adb184c22de6662545eee84a3acb5d1da2a606d31da977b23bbb330b21"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "2f4cb7e3686c2ca90a40574a1a4b65e227c86e7073cc4d1fc33798e78b4d086d"
metafile = true

[[files]]
file = "mods/appleskin.toml"
hash = "e239b7756304259d632a59d74b5672a78b63041c9d24bd449dd5863f699d7cde"
metafile = true

[[files]]
file = "mods/architectury-fabric.toml"
hash = "706dfaef55d666502cbb27309ef3b7a7e281078b7275f8025c3698c553cd1b38"
metafile = true

[[files]]
file = "mods/auroras-decorations.toml"
hash = "d25f599d055a314ac8b0be5aa6aff0e4be1f1e5a887e3b3c9e42f0adec2edbe1"
metafile = true

[[files]]
file = "mods/better-mount-hud.toml"
hash = "757207131774e618e46c6c0ad407c8ba7c45d3c9c4fb59ffa8209d1bfe04a0d8"
metafile = true

[[files]]
file = "mods/blur-fabric.toml"
hash = "f781e21b5f5ac35b6b9be2a8219dcce459ad7564581c2f9a1c83059b48c82efc"
metafile = true

[[files]]
file = "mods/borderless-mining.toml"
hash = "953fea75f93a02085a416200edb491e61accdfe19ed74c80b3c5269e6436289e"
metafile = true

[[files]]
file = "mods/capes.toml"
hash = "a95e949723e71f98bf649883fa694950805f0431074e2716a4d769d3d2fddf9c"
metafile = true

[[files]]
file = "mods/caracal-mod.toml"
hash = "575f692b8cc258f23fa468f971d63802398f276fa1dbee0377e3f34f1a324260"
metafile = true

[[files]]
file = "mods/cc-restitched.toml"
hash = "b08dbfc5b377c0c1eb4ca16449091340c0737074a96275100d942b64a3c2b199"
metafile = true

[[files]]
file = "mods/cem.toml"
hash = "727c319290b015a46f54f379fdb32b1a8eeb649c85bb7409fe3b9ffd3ebe5d22"
metafile = true

[[files]]
file = "mods/cit-resewn.toml"
hash = "514fca35d56842bf057e04b93848ef977156678bfc8949dfa2cdb2cdc04a7a0e"
metafile = true

[[files]]
file = "mods/cloth-api.toml"
hash = "9a7b7e2fdf34fa4fe0b7937c3a6b9e96d0c40fedc3a2da93b5c40be222dd43f2"
metafile = true

[[files]]
file = "mods/cloth-config.toml"
hash = "010bc8378b59257708190728f5aee476d7415f47fc26567952f294eda6b0cd25"
metafile = true

[[files]]
file = "mods/collective-fabric.toml"
hash = "a9b361789fc8693e171d1c33ec07785995f610436b9bf70c21cd5fb334306b2b"
metafile = true

[[files]]
file = "mods/completeconfig.toml"
hash = "cdf2fa71fe664058284a09f475f87d07ac4f4556932d963e3904d3967129a9a4"
metafile = true

[[files]]
file = "mods/consistencyplus.toml"
hash = "a9ece9d270eea0de9c26c306fc83da769ee75c082a0967bc691f52e6ac900f4e"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "4a45496d6a0cd4cd445e300791af4473587864d20024d8c1bd032e763c36b698"
metafile = true

[[files]]
file = "mods/couplings.toml"
hash = "4128591cf6f35dce8c576d03781b3bc540ea6053b216fb6f80627310c7498422"
metafile = true

#[[files]]
#file = "mods/create.toml"
#hash = "bd9549bc9c70b2aeefd1b327d7dd4f841718223984e84a1c34cf19c5c676077e"
#metafile = true

[[files]]
file = "mods/crooked-crooks.toml"
hash = "04c0d835cca4a8c9aab622808bcd43312619ed1818dcd7fea52a0863d661adb4"
metafile = true

[[files]]
file = "mods/dank-storage-fabric.toml"
hash = "46a2beb538e3e9c618f90ec5d4b645cefbdc9c0b8ba69efecaba24024820132d"
metafile = true

[[files]]
file = "mods/dashloader.toml"
hash = "22a9f27ba11eebe161bc6b7ae30aa1af90efe2a8b1cb84acd30cf164021fb77f"
metafile = true

[[files]]
file = "mods/dcch.toml"
hash = "f811170d884fbbe2ccbd8e5c42137eb490d0116255878f5b53336efafcb2877c"
metafile = true

[[files]]
file = "mods/disenchanter.toml"
hash = "118474aa9c8fb8ee0f7881ec5d0af48b67024a83973e4eb3a6c42feaad6e4ac7"
metafile = true

[[files]]
file = "mods/dual-riders.toml"
hash = "63be8058d8ba5b0e5b322c264e7b716db8c882a2e2114c22ba00d84144f26e84"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "ffc1f6d147394bfeb65b2fb9a78ca7d3365cbf5192c31af1312bc899190e4e34"
metafile = true

[[files]]
file = "mods/effective.toml"
hash = "aa6ebc926e27070f0a4612dc72db4c5b2cbe2f2a70ff7816feed142c430e3531"
metafile = true

[[files]]
file = "mods/enhanced-block-entities.toml"
hash = "69aeed63058057dc3564d7487402fad911901b0927f96039559dac33205d2a9f"
metafile = true

[[files]]
file = "mods/enhancedquarries.toml"
hash = "2b2359300a5af48da93d6c3fe6ab3036ae25cbcaa88702d653621f185b476577"
metafile = true

[[files]]
file = "mods/entityculling.toml"
hash = "c2ee93e74ad106f20b997ffb054f46189f941da0c37c73a1a97d5dd85ff530a5"
metafile = true

[[files]]
file = "mods/experience-bottler.toml"
hash = "d95190864742e3f6bbeb9e03e9aac116e9ddfe57db0fc2a809bc888fe4ea48c3"
metafile = true

[[files]]
file = "mods/extra-generators.toml"
hash = "827c908e9614996ce3a70ebe0864b53bda09bba2e4e88b24913388c8f8aafc44"
metafile = true

[[files]]
file = "mods/extraalchemy.toml"
hash = "f027141937c15be2eeb87d4dc9869050f1e57844ef3641795e00a532b266be0d"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "d09e22b6960590df5462182e20545907bd89ae1f55ae48dfb1134ba5588572ba"
metafile = true

[[files]]
file = "mods/fabric-chisel.toml"
hash = "2f142f438cc1f9114eccb37c2fd374121a561ee40ff7b2222582abe8b6d9e75b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "738ffde3eab8e9d0c616e419862ff9c588bbd6009fad70953bd4d4697c88f202"
metafile = true

[[files]]
file = "mods/fabrishot.toml"
hash = "14c5788025b1a75cb738143110ec69fa0f9775e9e38e8002399a7efa095f512f"
metafile = true

[[files]]
file = "mods/farmers-delight-fabric.toml"
hash = "f27bb409bcc2145ff98e41db4646829d9598457217b86c85d83a7f286198fb4e"
metafile = true

[[files]]
file = "mods/fastopenlinksandfolders.toml"
hash = "a401eef95d8cd5100179ac77d1b78b7172b98d8fe1d8c5b17a751854d2db88d0"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "32f86897ed44b041a79f0f90246ac35b400a427f7c206140007b6a9939a225b5"
metafile = true

[[files]]
file = "mods/flesh2leather-fabric.toml"
hash = "cfd53be5cb696b36916cad0761b0012f17630f830d73f8d3953c84cb40c57455"
metafile = true

[[files]]
file = "mods/full-slabs.toml"
hash = "d0b02d8889d7888276aaa3eea2ecb63ddb7fb7c14408c5d18fe36c31ecdef0a6"
metafile = true

[[files]]
file = "mods/go-fish.toml"
hash = "0c1b9817367d47f97639fb4e8757c5d18bb7809de5c25f0e10bc5df9de3c7fde"
metafile = true

[[files]]
file = "mods/illuminations.toml"
hash = "70a675720e61af18f8551dd4d49d3a6d2af8402c6a4ba74adaa8dd2d1f0a72b1"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "c94fbad1b3dd7973d2b0f33b03b4683875a0f95ffe0db3be4c90a946a29bb353"
metafile = true

[[files]]
file = "mods/industrial-revolution.toml"
hash = "01f9c94f4bd00fb95b1809a16dcdc08837f7c485764742be3548bbfef3d4f48f"
metafile = true

[[files]]
file = "mods/inventorio.toml"
hash = "bfdecd17a9fce3e979d36d75f73620bced71f60fe70dc69ed66b25001368d98d"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "f5f2860059ab91478fa3be83da7afd4be60f7fc3462ea2714240a8363c12ec5d"
metafile = true

[[files]]
file = "mods/item-model-fix.toml"
hash = "9ab8949bcb4280b1a4b97d40ded17b4786a6c4db1271c121a7fc52ea6f838e0e"
metafile = true

[[files]]
file = "mods/just-mob-heads-fabric.toml"
hash = "dfca9d2a4c58b19a1472fdd68c2dbe361447b997eed61676864d3d1a799b2948"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
hash = "d0cf8f6847a6c3f18010788f1068b98abb0ebca06536d2f482dc51d834a31308"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "158c40f09b2ed4fe14f5f2925751796fe11f6baee7e1ac7f35931ad831631a3d"
metafile = true

[[files]]
file = "mods/language-reload.toml"
hash = "2c410266c2e5763c5ebaaedbe68519920e857c8d6edac44aadefa2b407d016f5"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "ea127e8f74006f3a9ce099f9e96adaa3b3f4f281231ece703c4e7f9732137ebd"
metafile = true

[[files]]
file = "mods/leaf-decay.toml"
hash = "e8fc1336a2f15d102123771bd8ddb6ca1a8757aaf6800610000483ce9369c105"
metafile = true

[[files]]
file = "mods/lib.toml"
hash = "112d4971866f902787731385ccf1eb68d59367646bef15cc2921095412b715c9"
metafile = true

[[files]]
file = "mods/libblockattributes.toml"
hash = "52d36de6f3d8de19d8d0da46ae3cf71f8edddcecaabcd52c5a8bc7ff6d687612"
metafile = true

[[files]]
file = "mods/lifts.toml"
hash = "08033dd50f48e9d8a8207e0f13f4e491e748e104d85e0099a6ac7a26e5fc1c22"
metafile = true

[[files]]
file = "mods/malilib.toml"
hash = "48d7d8ddf473e8877ac11527859219badc30e0e9732200100ef206bc7d08cb65"
metafile = true

[[files]]
file = "mods/megane.toml"
hash = "8ac938adebe88d9cd39c4dfa97522b35125158a59e580ecb769d9b36bde65d17"
metafile = true

[[files]]
file = "mods/mo-glass.toml"
hash = "0281096a9a1b0f7567fc23d8059d31c436904999f30f35cc21bcd0143dad806b"
metafile = true

[[files]]
file = "mods/mo-structures.toml"
hash = "b7e8b3c60482a0fd616ea9251d7733e40bf2cf758fdf51647878d45965c1b57f"
metafile = true

[[files]]
file = "mods/modern-industrialization.toml"
hash = "470467ac3959e03ecc74d1b265cfb9fe21d10f9c0972661de530a35135b77c56"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "08cf57c2cae5fff7f0b8d043c45df07893ea01734a6486f9ca94caae741ea351"
metafile = true

[[files]]
file = "mods/morechathistory.toml"
hash = "3da1c6f350407d59ac89fdaf76f28b53b96ab40267edd3f750d9f4c482327d5d"
metafile = true

[[files]]
file = "mods/mouse-wheelie.toml"
hash = "9845e137682e6763c8046ce9b9bbfae52f59ea3ec5f57d98ea9921a9f3d9c1cd"
metafile = true

[[files]]
file = "mods/no-cap-anvil.toml"
hash = "caf4e9fbb297e3597d449d2ad346db410a21bbb1ecf73ea9b42984c1c6e0b178"
metafile = true

[[files]]
file = "mods/no-fade.toml"
hash = "11e9ff4826221962d98b9442e61beeead0872693bdb9abcae72edd8db0993fdf"
metafile = true

[[files]]
file = "mods/no-telemetry.toml"
hash = "bcbc4091875a9f83813374950be1b9a1f89ac26f393afa54c85c29614069acf4"
metafile = true

[[files]]
file = "mods/pipe.toml"
hash = "74997dc610ef84623892a9763484e8aa96b09204ade1ba879d0a39c64c90f4f0"
metafile = true

[[files]]
file = "mods/presence-footsteps.toml"
hash = "210d68d18e3e8582c1ffa6ba118ee2bb3d480bf18484e3b0cc8215a39c84341b"
metafile = true

[[files]]
file = "mods/roughly-enough-items.toml"
hash = "ee3187bfac3961c573a8e00edd0d2f69e66c4aeb9a65f203781ab1687e2d3856"
metafile = true

[[files]]
file = "mods/roughly-enough-resources.toml"
hash = "9c51dd2b58c2e58340ac042813309f6cc2b02b661be58a2ff5652824bdb45967"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.toml"
hash = "48d086c6bec06c3eecf43f89c643b59fc116f80b6ac7444c68a379b2daa8de08"
metafile = true

[[files]]
file = "mods/simple-voice-chat.toml"
hash = "f8ee1f3712bb05a1550d9a4530e66802008eb8db9475c911f8aed321d4f7246b"
metafile = true

[[files]]
file = "mods/skin-layers-3d.toml"
hash = "56acb7111d461ab212050d208a66a0d0dd890ee2d8961542bc302c0f239d9946"
metafile = true

[[files]]
file = "mods/smooth-boot.toml"
hash = "5395f3c793c9d31347774b1a179c6287958df953f0bf9652b6953673f74e7e08"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
hash = "f0ab553dfbd753da7774768a0589771b9bf1f4157d3735315fd6aca5c0c16322"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "f291cfa3dc4468318494015a4d695f66a22356355aa0122b2fbb7c1407ffdde0"
metafile = true

[[files]]
file = "mods/spark.toml"
hash = "a76e869bbe7c1353fc2f472234a820927be2b576d768e019531d7effb86a5855"
metafile = true

[[files]]
file = "mods/techreborn.toml"
hash = "99921192f4c54a05108411e971d2968ec5489aafda2de1f35de8095632a9d7b4"
metafile = true

[[files]]
file = "mods/tooltipfix.toml"
hash = "57279a8ae2d7c6e5053da3909d95254118db533d9a38c1a0763bf602d80c933d"
metafile = true

[[files]]
file = "mods/trinkets.toml"
hash = "1da8fd5d697f28be3aaedaed8a6a8c88a7d627e6d5b5478342f73368dd3d0ac8"
metafile = true

[[files]]
file = "mods/upc.toml"
hash = "ff82170c70d27bddc5861f4ea7bd08b710bd4d104df26d95c126a1ef429b4edb"
metafile = true

[[files]]
file = "mods/waveycapes.toml"
hash = "417d84bf61f1db58accb400b2d935546a54990615ebe320a9de27722d53334e2"
metafile = true

[[files]]
file = "mods/where-is-it.toml"
hash = "fc43f59bf9f8538e633d4910bdf87d6980719c78682976de05f6329530781100"
metafile = true

[[files]]
file = "mods/wicked-paintings.toml"
hash = "8bb409758a2ae89f3766660c1402f102e8c8bd7f83fbe49b68940546ab7946dd"
metafile = true

[[files]]
file = "mods/wthit.toml"
hash = "2d2e610a39c8802ae2899fe6ee6f81c84562ea54629e8fb7337f3abee8cf4bc3"
metafile = true

[[files]]
file = "mods/xaeros-minimap.toml"
hash = "6c3e91ec40a8523e5e25f285435b2031900aa5275a519755f0e0d4e6c2508df6"
metafile = true

[[files]]
file = "mods/xaeros-world-map.toml"
hash = "3387843633739f2242e29e3186f3387be92bcf63674574955caa96e94bd308fe"
metafile = true

[[files]]
file = "mods/yosbr.toml"
hash = "527e21c9bc55b0d1db9016a2fec4ff2dee2a93c53edb8c1363d2d2ee7730afd0"
metafile = true
